const V=[
{id:1,name:'Honda City',type:'Car',rate:1499,status:'Available'},
{id:2,name:'Toyota Glanza',type:'Car',rate:1299,status:'Available'},
{id:3,name:'Hyundai i20',type:'Car',rate:1199,status:'Booked'},
{id:4,name:'Royal Enfield Classic',type:'Bike',rate:699,status:'Available'},
{id:5,name:'Yamaha R15',type:'Bike',rate:799,status:'Booked'},
{id:6,name:'Honda Activa',type:'Bike',rate:499,status:'Available'}];
const demoCustomers=[['CUST001','Arun Kumar','arun@example.com'],['CUST002','Nived S','nived@example.com'],['CUST003','Rahul P','rahul@example.com']];
function bookings(){return JSON.parse(localStorage.getItem('driveeaseBookings')||'[]')}
const content=document.getElementById('adminContent'),title=document.getElementById('sectionTitle');
function overview(){const b=bookings();content.innerHTML=`<div class="kpi-grid"><div class="kpi"><small>Total Vehicles</small><strong>${V.length}</strong></div><div class="kpi"><small>Available Now</small><strong>${V.filter(v=>v.status==='Available').length}</strong></div><div class="kpi"><small>Reservations</small><strong>${b.length+8}</strong></div><div class="kpi"><small>Revenue</small><strong>₹${(b.reduce((s,x)=>s+x.total,0)+28450).toLocaleString('en-IN')}</strong></div></div><div class="grid2"><div class="panel"><h3>Recent Reservations</h3>${recentTable(b)}</div><div class="panel"><h3>Fleet Status</h3>${V.map(v=>`<p style="display:flex;justify-content:space-between"><span>${v.name}</span><span class="badge ${v.status==='Available'?'available':'booked'}">${v.status}</span></p>`).join('')}</div></div>`}
function recentTable(b){const rows=b.slice(-5).reverse();return rows.length?`<div class="table-wrap"><table class="admin-table"><tr><th>ID</th><th>Vehicle</th><th>Customer</th><th>Status</th></tr>${rows.map(x=>`<tr><td>${x.id}</td><td>${x.vehicle}</td><td>${x.customer}</td><td><span class="badge available">${x.status}</span></td></tr>`).join('')}</table></div>`:'<div class="empty">No new bookings. Demo data will appear here after a customer makes a reservation.</div>'}
function vehicles(){content.innerHTML=`<div class="panel"><div class="section-actions"><h3>Fleet Management</h3><button class="admin-btn" onclick="alert('Add Vehicle form can be connected to Java/MySQL later.')">+ Add Vehicle</button></div><div class="table-wrap"><table class="admin-table"><tr><th>ID</th><th>Vehicle</th><th>Type</th><th>Rate/day</th><th>Status</th><th>Action</th></tr>${V.map(v=>`<tr><td>V00${v.id}</td><td><b>${v.name}</b></td><td>${v.type}</td><td>₹${v.rate}</td><td><span class="badge ${v.status==='Available'?'available':'booked'}">${v.status}</span></td><td><button class="admin-btn" onclick="alert('Edit ${v.name}')">Edit</button></td></tr>`).join('')}</table></div></div>`}
function allBookings(){const b=bookings();content.innerHTML=`<div class="panel"><div class="section-actions"><h3>Reservation Management</h3><span class="badge pending">${b.length} live booking(s)</span></div>${b.length?`<div class="table-wrap"><table class="admin-table"><tr><th>Booking</th><th>Vehicle</th><th>Customer</th><th>Dates</th><th>Amount</th><th>Status</th></tr>${b.slice().reverse().map(x=>`<tr><td>${x.id}</td><td>${x.vehicle}</td><td>${x.customer}<br><small>${x.email}</small></td><td>${x.pickup}<br>${x.returnDate}</td><td>₹${x.total.toLocaleString('en-IN')}</td><td><span class="badge available">${x.status}</span></td></tr>`).join('')}</table></div>`:'<div class="empty">No customer bookings yet.</div>'}</div>`}
function customers(){content.innerHTML=`<div class="panel"><h3>Customer Management</h3><div class="table-wrap"><table class="admin-table"><tr><th>ID</th><th>Name</th><th>Email</th><th>Bookings</th></tr>${demoCustomers.map((c,i)=>`<tr><td>${c[0]}</td><td>${c[1]}</td><td>${c[2]}</td><td>${i+1}</td></tr>`).join('')}</table></div></div>`}
function reports(){const b=bookings(),rev=b.reduce((s,x)=>s+x.total,0)+28450;content.innerHTML=`<div class="report-grid"><div class="report-box"><small>Monthly Revenue</small><strong>₹${rev.toLocaleString('en-IN')}</strong><p>Rental income recorded</p></div><div class="report-box"><small>Fleet Utilization</small><strong>67%</strong><p>Vehicles currently utilized</p><div class="progress"><i style="width:67%"></i></div></div><div class="report-box"><small>Customer Satisfaction</small><strong>4.7/5</strong><p>Based on demo records</p></div></div><div class="panel" style="margin-top:15px"><h3>Management Notes</h3><p style="color:#7d8798;line-height:1.7">This frontend admin dashboard is a prototype. In the final Java project, these values should be loaded from the backend and MySQL database.</p></div>`}
function show(sec){title.textContent=sec[0].toUpperCase()+sec.slice(1);({overview,vehicles,bookings:allBookings,customers,reports}[sec]||overview)();document.querySelectorAll('.side-link[data-section]').forEach(x=>x.classList.toggle('active',x.dataset.section===sec))}
document.querySelectorAll('.side-link[data-section]').forEach(x=>x.addEventListener('click',()=>show(x.dataset.section)));
document.getElementById('adminLogout').addEventListener('click',()=>location.href='../home.html');show('overview');