package com.vehiclerental.controller;
import com.vehiclerental.entity.*; import com.vehiclerental.repository.*; import org.springframework.http.ResponseEntity; import org.springframework.web.bind.annotation.*; import java.time.LocalDate; import java.time.temporal.ChronoUnit; import java.util.List;
@RestController @RequestMapping("/api/reservations") @CrossOrigin(origins="*") public class ReservationController {
 private final ReservationRepository reservations; private final VehicleRepository vehicles; private final CustomerRepository customers; public ReservationController(ReservationRepository r,VehicleRepository v,CustomerRepository c){reservations=r;vehicles=v;customers=c;}
 @GetMapping public List<Reservation> all(){return reservations.findAll();}
 @GetMapping("/customer/{customerId}") public List<Reservation> byCustomer(@PathVariable Long customerId){return reservations.findByCustomerIdOrderByIdDesc(customerId);}
 @GetMapping("/availability/{vehicleId}") public boolean available(@PathVariable Long vehicleId,@RequestParam LocalDate startDate,@RequestParam LocalDate endDate){return reservations.findByVehicleIdAndStatusAndStartDateLessThanEqualAndEndDateGreaterThanEqual(vehicleId,"CONFIRMED",endDate,startDate).isEmpty();}
 @PostMapping public ResponseEntity<?> create(@RequestBody Reservation r){if(r.getCustomerId()==null||r.getVehicleId()==null||r.getStartDate()==null||r.getEndDate()==null)return ResponseEntity.badRequest().body("Customer, vehicle and dates are required");if(!customers.existsById(r.getCustomerId()))return ResponseEntity.badRequest().body("Customer account not found. Please login or register.");if(r.getEndDate().isBefore(r.getStartDate()))return ResponseEntity.badRequest().body("Return date cannot be before pickup date");if(!reservations.findByVehicleIdAndStatusAndStartDateLessThanEqualAndEndDateGreaterThanEqual(r.getVehicleId(),"CONFIRMED",r.getEndDate(),r.getStartDate()).isEmpty())return ResponseEntity.badRequest().body("Vehicle is not available for the selected dates");Vehicle v=vehicles.findById(r.getVehicleId()).orElse(null);if(v==null)return ResponseEntity.badRequest().body("Vehicle not found");if(!v.isAvailable())return ResponseEntity.badRequest().body("Vehicle is currently unavailable");long days=Math.max(1,ChronoUnit.DAYS.between(r.getStartDate(),r.getEndDate()));r.setTotalCost(days*v.getPricePerDay());r.setStatus("CONFIRMED");return ResponseEntity.ok(reservations.save(r));}
 @DeleteMapping("/{id}") public ResponseEntity<?> cancel(@PathVariable Long id){return reservations.findById(id).map(r->{r.setStatus("CANCELLED");reservations.save(r);return ResponseEntity.ok("Reservation cancelled");}).orElse(ResponseEntity.notFound().build());}
}